# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

# on indique quand est-ce que l'action est lancé
on:
  push:
    branches: ["main"]
  # pull_request

jobs:  # exécution de ce que je veux lancer
  build:

    runs-on: ubuntu-latest  # version  de l'os du serveur qui va lancer le script
    permissions:
      contents: read
      packages: write

    steps:  # toutes les étapes à valider avec de push sur un endroit du repo
    - uses: actions/checkout@v4  # permet de réccupérer les fichiers du git
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: hello world
      #run: echo 'coucou' # tout est possible en shell
      run: wft
      
    - name: Build with Maven  # avantage du build maven : lance les tests :)
      run: mvn -B package --file pom.xml
